name: Deploy to Cloudflare pages

inputs:
  apiToken:
    required: true
    type: string
  accountId:
    required: true
    type: string

outputs:
  url:
    value: ${{ steps.pages.outputs.url }}

runs:
  steps:
    - run: |
        mkdir build
        echo "test" >> build/index.html
    - name: Deploy to Cloudflare Pages
      id: pages
      run: |
        npx wrangler pages publish build --project-name=calamar --branch="${{ github.ref_name }}"
        URL=$(curl -s 'https://api.cloudflare.com/client/v4/accounts/${{ inputs.accountId }}/pages/projects/calamar/deployments' \
          --header 'Authorization: Bearer ${{ inputs.apiToken }}' \
          | jq -r '[ .result[] | select(.is_skipped == false and .deployment_trigger.metadata.branch == "${{ github.ref_name }}") ] | .[0].url')
        echo "url=${URL}" >> $GITHUB_OUTPUT
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.apiToken }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.accountId }}
