name: Cache node modules

inputs:
  install:
    type: boolean
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true' && inputs.install == 'true'
      run: npm ci
