name: Install Playwright browsers

runs:
  using: "composite"
  steps:
    - name: Cache Playwright browsers
      id: cache-playwright-browsers
      uses: actions/cache@v3
      env:
        cache-name: cache-playwright-browsers
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install playwright-browsers
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps
