name: Deploy to Cloudflare pages

inputs:
  accessToken:
    required: true
    type: string
  environment:
    required: true
    type: string
  version:
    required: false
    default: ${{ github.sha }}
    type: string
  urls:
    required: true
    type: string
  path:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Collect sourcemaps
      id: collect_sourcemaps
      shell: bash
      run: |
        cd ${{ inputs.path }}; \
        for url in ${{ inputs.urls }}; do \
          for file in $(find . -name "*.js" -printf "%P "); do \
            if [ -f "$file.map" ]; then \
              MINIFIED_URLS="${MINIFIED_URLS} $url/$file"; \
              SOURCE_MAPS="${SOURCE_MAPS} build/$file.map"; \
            fi; \
          done; \
        done; \
        echo "${MINIFIED_URLS}"; \
        echo "${SOURCE_MAPS}"; \
        echo "minified_urls=${MINIFIED_URLS}" >> $GITHUB_OUTPUT; \
        echo "source_maps=${SOURCE_MAPS}" >> $GITHUB_OUTPUT;
    - name: Deploy to Rollbar
      uses: rollbar/github-deploy-action@2.1.1
      with:
        environment: ${{ inputs.environment }}
        version: ${{ inputs.version }}
        source_maps: ${{ steps.collect_sourcemaps.outputs.source_maps }}
        minified_urls: ${{ steps.collect_sourcemaps.outputs.minified_urls }}
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ inputs.accessToken }}
