name: Deploy to Cloudflare pages

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir build
          echo "test" >> build/index.html
      - name: Deploy to Cloudflare Pages
        id: pages
        run: |
          npx wrangler pages publish build --project-name=calamar --branch="${{ github.ref_name }}"
          URL=$(curl -s 'https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/calamar/deployments' \
            --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
            | jq -r '[ .result[] | select(.is_skipped == false and .deployment_trigger.metadata.branch == "${{ github.ref_name }}") ] | .[0].url')
          echo "url=${URL}" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
