name: Up to date

on:
  push:
    branches:
      - wip-up-to-date

jobs:
  rerun-up-to-date:
    name: Re-run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Rerun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env
          gh pr list --base ${GITHUB_REF_NAME}
