name: Up to date

on:
  push:
    branches:
      - wip-up-to-date

jobs:
  rerun-up-to-date:
    name: Re-run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Re-run checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env
          BRANCHES=$(gh pr list --base ${GITHUB_REF_NAME} --json headRefName --jq '.[].headRefName')
          echo $BRANCHES
          RUNS=$(for i in $BRANCHES; do gh run list -b $i -w up-to-date.yml -L 1 --json databaseId --jq '.[].databaseId'; done)
          echo $RUNS
          for i in $RUNS; do \
            gh run cancel $i > /dev/null || true; \
            gh run watch $i > /dev/null; \
            gh run rerun $i; \
            echo "$i re-runned"; \
          done
