name: Up to date

on:
  push:
    branches:
      - wip-up-to-date

jobs:
  rerun-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Rerun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          env
          gh pr list --base ${GITHUB_REF_NAME}
