name: Check if up to date

on:
  pull_request:

jobs:
  up-to-date:
    name: Is up to date with base branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if up to date
        run: |
          env | sort
          pwd
          ls -la
          ls -la ${{ github.action_path }}
          git status
          git fetch
          git status
          git branch
          BEHIND=$(git rev-list --left-right --count ${GITHUB_BASE_REF}...${GITHUB_HEAD_REF} | cut -f1)
          git rev-list --left-right --count ${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}
          echo $BEHIND
          test $BEHIND -eq 0
