name: Check if up to date

on:
  pull_request:

jobs:
  up-to-date:
    name: Is up to date with base branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if up to date
        run: |
          env | sort
