# This workflow is used to check if the branch is up-to-date with master branch.
#
# The reason why this is used instead of protecting master branch and require
# other branches to be up to date before merging by setting in github settings,
# is because this setting also requires at least one status check which prevents
# direct pushes to the master branch so every push needs to be done to a separate
# branch first which is very inconvenient.

name: Up to date

on:
  pull_request:
    branches:
      - master

jobs:
  up-to-date:
    name: Is up to date with base branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if up to date
        run: |
          env | sort
          BEHIND=$(git rev-list --left-right --count origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} | cut -f1)
          echo $BEHIND
          test $BEHIND -eq 0
